### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by MajedSardar64** [mablay/pdf-export-images#1]
Error:
Something went wrong installing the "sharp" module

**Comment by mablay** [comment]
You seem to be facing an issue with the sub-dependency module: "sharp".
Do you experience the same problem, when you install and use sharp directly?
I failed to reproduce the error. Do you have a github link to the repository in which the problem occurs?

**Comment by mablay** [comment]
I updated all dependencies, including "sharp". Please try v1.2.0. If that doesn't help, see the previous comment.

**Comment by awais-yousaf** [comment]
> Error: Something went wrong installing the "sharp" module

Make sure you are using the right sharp package for installation. Depending on your CPU architecture you might need to install a different version of Sharp separately.
Check this for more information related to installation: https://sharp.pixelplumbing.com/install

**Comment by MajedSardar64** [comment]
thank you. it's works 


Such an application would be much better in php.
